# install java 8
FROM openjdk:8-jdk-alpine

EXPOSE 8080

# Work directory 
WORKDIR /usr/src/app

# Copy project files
COPY . .

# Build project
RUN ./mvnw package

CMD ["java","-jar", "./target/docker-example-1.1.3.jar"]


