version: "6.9"

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    container_name: simple-web-service
    volumes:
      - ./text.log:/usr/src/app/text.log # Maps the log file from the container to the host
    ports:
      - 8080:8080 # Maps port 8080 of the container to port 8080 on the host
